controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

    torso_test_fts_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    left_fts_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

position_controller:
  ros__parameters:
    joints:
      - right_shoulder_pitch
      - right_shoulder_roll
      - right_elbow
      - left_shoulder_pitch
      - left_shoulder_roll
      - left_elbow
      - head_yaw
      - head_pitch
      - right_hip_pitch
      - right_hip_roll
      - right_hip_yaw
      - right_knee
      - right_ankle_pitch
      - left_hip_pitch
      - left_hip_roll
      - left_hip_yaw
      - left_knee
      - left_ankle_pitch
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: "torso_imu"
    frame_id: "torso_imu"

torso_test_fts_broadcaster:
  ros__parameters:
    sensor_name: "torso_test_fts"
    frame_id: "torso_test"

force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: "right_foot_sole_fts" # Back to original right foot sensor
    frame_id: "feet_sole"             # Must match the 'frame_id' in URDF <sensor> tag's param

left_fts_broadcaster:
  ros__parameters:
    sensor_name: "left_foot_sole_fts"   # Must match the 'name' in URDF <sensor> tag
    frame_id: "feet_2_sole"             # Must match the 'frame_id' in URDF <sensor> tag's param