controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # imu_sensor_broadcaster:
    #   type: imu_sensor_broadcaster/IMUSensorBroadcaster

    # torso_test_fts_broadcaster:
    #   type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    # right_fts_broadcaster:
    #   type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    # left_fts_broadcaster:
    #   type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

position_controller:
  ros__parameters:
    joints:
      - right_elbow
      - right_shoulder_roll
      - right_shoulder_pitch
      - left_elbow
      - left_shoulder_roll
      - left_shoulder_pitch
      - head_pitch
      - head_yaw
      - right_ankle_pitch
      - right_knee
      - right_hip_yaw
      - right_hip_roll
      - right_hip_pitch
      - left_ankle_pitch
      - left_knee
      - left_hip_yaw
      - left_hip_roll
      - left_hip_pitch
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: "torso_imu"
    frame_id: "torso_imu"

torso_test_fts_broadcaster:
  ros__parameters:
    sensor_name: "torso_test_fts"
    frame_id: "torso_test"

right_fts_broadcaster:
  ros__parameters:
    sensor_name: "right_foot_sole_fts"
    frame_id: "right_foot_sole"

left_fts_broadcaster:
  ros__parameters:
    sensor_name: "left_foot_sole_fts"
    frame_id: "left_foot_sole"
